<template>
  <nav class="grid grid-cols-2 md:grid-cols-4 gap-y-12 uppercase">
    <div class="space-y-12">
      <div>
        <HeadingSans>
          Friends
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-teal-500"
              external="true"
              id="Conceived_in_Fire"
              to="https://twitch.tv/Conceived_in_Fire"
            >
              Conceived_in_Fire
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-teal-500"
              external="true"
              id="CthulhuRei"
              to="https://twitch.tv/CthulhuRei"
            >
              CthulhuRei
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
    <div class="space-y-12">
      <div>
        <HeadingSans>
          —
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-teal-500"
              external="true"
              id="CreepyCrappyShow"
              to="https://twitch.tv/CreepyCrappyShow"
            >
              CreepyCrappyShow
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-teal-500"
              external="true"
              id="pedroleitin"
              to="https://twitch.tv/pedroleitin"
            >
              pedroleitin
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
    <div class="space-y-12">
      <div>
        <HeadingSans>
          —
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-teal-500"
              external="true"
              id="naweskil"
              to="https://twitch.tv/naweskil"
            >
              naweskil
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-teal-500"
              external="true"
              id="pedroturambar"
              to="https://twitch.tv/pedroturambar"
            >
              pedroturambar
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
    <div class="space-y-12">
      <div>
        <HeadingSans>
          —
        </HeadingSans>
        <ul role="list" class="mt-6 space-y-3">
          <li>
            <NavigationLink
              color="hover:text-teal-500"
              external="true"
              id="podrivo"
              to="https://twitch.tv/podrivo"
            >
              podrivo
            </NavigationLink>
          </li>
          <li>
            <NavigationLink
              color="hover:text-teal-500"
              external="true"
              id="quietsurvivor"
              to="https://twitch.tv/quietsurvivor"
            >
              quietsurvivor
            </NavigationLink>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>
